name = "natural"
pages_build_output_dir = "out"
compatibility_date = "2026-07-18"

[[d1_databases]]
binding = "BLOG_DB"
database_name = "natural-fitness-blog"
database_id = "15bf52fa-dd59-4258-9198-ed3e746ea53f"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "natural-fitness-media"
